/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UspBtn {
    }
}
declare global {
    interface HTMLUspBtnElement extends Components.UspBtn, HTMLStencilElement {
    }
    var HTMLUspBtnElement: {
        prototype: HTMLUspBtnElement;
        new (): HTMLUspBtnElement;
    };
    interface HTMLElementTagNameMap {
        "usp-btn": HTMLUspBtnElement;
    }
}
declare namespace LocalJSX {
    interface UspBtn {
    }
    interface IntrinsicElements {
        "usp-btn": UspBtn;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "usp-btn": LocalJSX.UspBtn & JSXBase.HTMLAttributes<HTMLUspBtnElement>;
        }
    }
}
