/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UspBtn {
        /**
          * Color token (e.g. "primary-500", "accent-100") or hex code (e.g. "#FF5733").
         */
        "color"?: string;
        /**
          * Whether the button is disabled.
         */
        "disabled": boolean;
        /**
          * Button size ("sm", "md", "lg").
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The HTML type of the button ("button", "submit", or "reset").
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Variant of the button ("flat" or "outlined").
         */
        "variant": 'flat' | 'outlined';
    }
}
declare global {
    interface HTMLUspBtnElement extends Components.UspBtn, HTMLStencilElement {
    }
    var HTMLUspBtnElement: {
        prototype: HTMLUspBtnElement;
        new (): HTMLUspBtnElement;
    };
    interface HTMLElementTagNameMap {
        "usp-btn": HTMLUspBtnElement;
    }
}
declare namespace LocalJSX {
    interface UspBtn {
        /**
          * Color token (e.g. "primary-500", "accent-100") or hex code (e.g. "#FF5733").
         */
        "color"?: string;
        /**
          * Whether the button is disabled.
         */
        "disabled"?: boolean;
        /**
          * Button size ("sm", "md", "lg").
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The HTML type of the button ("button", "submit", or "reset").
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Variant of the button ("flat" or "outlined").
         */
        "variant"?: 'flat' | 'outlined';
    }
    interface IntrinsicElements {
        "usp-btn": UspBtn;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "usp-btn": LocalJSX.UspBtn & JSXBase.HTMLAttributes<HTMLUspBtnElement>;
        }
    }
}
